name: "Application Firewall Logging"
description: "This Unified Log filter may be used to report on logging from the Application Firewall in macOS. this filter functions by monitoring logging from the com.apple.alf subsystem."
predicate: "subsystem == "com.apple.alf""
tags: 
  - visibility
enabled: true

# If executing these commands locally in Terminal "sudo" will be required.

# By default private data (such as IP addresses and ports) will be redacted by Apple"s Private Logging feature.  In order to disable this for the Application Firewall logging specifically this configuration profile may be enforced:
# https://github.com/usnistgov/macos_security/blob/monterey/includes/com.apple.alf.private_data.mobileconfig
