name: "Modification of DNS Settings"
description: "This Unified Log filter may be used to report on enabling or disabling the DNS Settings filter in Network Preferences.
  This filter functions by monitoring logging from the NetworkExtension subsystem and nehelper nesessionmanager process and event message containing a string known to indicate enablement or disablement of the DNS Settings filter in Network System Preferences."
predicate: "subsystem == "com.apple.networkextension" and process == "nehelper" and eventMessage CONTAINS "DNS settings are enabled" OR subsystem == "com.apple.networkextension" and process == "nesessionmanager" and eventMessage contains "status changed to disconnected, last stop reason Configuration was disabled""
tags:
  - visibility
enabled: true